### ISSUE TITLE
DRUG_ERA/Age Decile Font Too Large

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#1]
- http://hixbeta.jnj.com/penelope/#/
- click on Celebrex
- Click Evidence Explorer
- Scoll down to DRUG_ERA

---

The text on this chart is too large, the index is over the y-axis label and the age categories are too large.

![image](https://cloud.githubusercontent.com/assets/6305439/10517965/491599ee-732d-11e5-866e-da52928dd773.png)

**Comment by chrisknoll** [comment]
This can be controled by CSS. It looks like in general the correct aspect ratio is beign used (sinc ethe inner-trellis numbers seem to be nicely sized, but the labels can be configured separately.  I'll try to put a PR to fix this.
