### ISSUE TITLE
Tegretol Label

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#19]
@jduke99 not sure if this is coming processed like this but in the tegretol label I'm seeing a broken tag.  

![image](https://cloud.githubusercontent.com/assets/6305439/10523382/32b4978e-7348-11e5-82a6-854ef1964132.png)

**Comment by ericaVoss** [comment]
In the same label I found another tag 
![image](https://cloud.githubusercontent.com/assets/6305439/10523447/86f482c8-7348-11e5-8477-7917b9bbd906.png)

**Comment by anthonysena** [comment]
These issues have been resolved in the new labels.
