### ISSUE TITLE
Search List - Default List and Filtering

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#2]
@jduke99  to provide drug search list for PENELOPE.  This needs to be integrated.  Right now it is just mocked up.

Also the search isn't actually filtering the list.

---

![image](https://cloud.githubusercontent.com/assets/6305439/10518144/064f1d3c-732e-11e5-82e0-45c07d9ad39f.png)

**Comment by pbr6cornell** [comment]
redundant with #11
