### ISSUE TITLE
Prevelances Are Off

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#23]
In the Observational Evidence the prevelances are way high.

![image](https://cloud.githubusercontent.com/assets/6305439/10548319/c73e38e6-7407-11e5-8044-cf3123e0b5a7.png)

**Comment by anthonysena** [comment]
Here is a link to the SQL file: https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/getDrugEraTreemap.sql

**Comment by pbr6cornell** [comment]
I think the length field is incorrectly put in the prevalence field.  The prevalence, which is percent_persons field from the SQL call, is in the dataset and should be shown instead

**Comment by pbr6cornell** [comment]
figured it out.
