### ISSUE TITLE
DB Definition - Add Patient Count for Demo Purposes

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#26]
![image](https://cloud.githubusercontent.com/assets/6305439/10548970/39fed594-740c-11e5-95e3-419c6ed3e7d0.png)

Could we rename the sources like this (Db Name (person count)).

Truven CCAE (APS) --> Truven CCAE (122M)
Truven MDCR (APS) --> Truven MDCR (9M)
Truven MDCD (APS) --> Truven MDCD (17M)
OPTUM (APS) --> Optum (41M)
CPRD (APS) --> CPRD (12M)
Premier (APS) --> Premier (108M)
JMDC (APS) --> JMDC (3M)
NHANES (APS) --> NHANES (72K)
OPTUM (SQL) -->  remove
Columbia --> Columbia (2M)
Truven MDCR (Postgresql) --> remove
Truven CCAE (SQL) --> remove
Truven MDCR (SQL) --> remove
Regenstrief Institute --> Regenstrief (12M)

I didn't know the counts on the last few.

**Comment by pbr6cornell** [comment]
Made the change for the demo.

**Comment by pbr6cornell** [comment]
don't think i updated the right place, or i have a caching issue...

**Comment by pbr6cornell** [comment]
it was a caching issue, now resolved
