### ISSUE TITLE
Label, hiding links from other sections

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Penelope#29]
Turn off for:
Indications and Usage
Dosage and Admininisrations
Dosage Forms and Strengths

Links should appear in:
Warning
Contraindication
Warnings & Precautions
Adverse Reaction

**Comment by jduke99** [comment]
Turn off for:
Indications and Usage
Dosage and Admininisrations
Dosage Forms and Strengths

Wouldn't worry about limiting which sections they get turned on for.  There are too many possible options.
