### ISSUE TITLE
FAERS - Graphics need to be Percentage

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Penelope#3]
On the Spontaneous Report Tabs we need to show percentages instead of raw numbers.

---

![image](https://cloud.githubusercontent.com/assets/6305439/10518251/8ca810c8-732e-11e5-832b-583ef7a501fc.png)

**Comment by chrisknoll** [comment]
Question about this:  woudln't raw numbers be more appropriate? the percentage is effectively the slice of the doughnut.  So, showing precentages would be redundant.  Counts, on the other hand, is additional information (unless you know the total # somewhere else in the figure).

**Comment by pbr6cornell** [comment]
no, we want %, not count.
