### ISSUE TITLE
Behavior of TOC needs revision

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Penelope#30]
1. All section headings should click to scroll the label text to that line as first line on page.  (right now, subheadings do it but major headings don't)
2. When you click on a word from the search, it should appear at top of search
3. On click, close TOC
4. search bar, change background color to white
5. when search word is found,  make font bigger and font color = yellow  so it stands out more
6. When you open TOC, a white bar appears at bottom of right-hand label, remove it.    (jon's hypothesis is there's a broken div that's probably the reason why #2 is not working, when you click on word, it goes to wrong location..)
7.  If you click on the search word multiple times, it should stay at same place, not jump around.

**Comment by jduke99** [comment]
Here is the weirdness I am seeing with TOC Open and Closed.  Basically, it shrinks the height of the panelBody when the TOC is open.

![normal without toc](https://cloud.githubusercontent.com/assets/5069947/10562352/ffd95496-7525-11e5-916c-1b2fe008f52d.PNG)

![with toc block](https://cloud.githubusercontent.com/assets/5069947/10562354/0d5b79f0-7526-11e5-8e03-143bd7d82bd6.PNG)

**Comment by anthonysena** [comment]
Most of these have been addressed so I am closing out this issue. I'm opening a new one to deal with a few of the lingering items from this issue as some will require some additional discussion.
