### ISSUE TITLE
Observational Evidence/Clinical Characterization

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Penelope#36]
We need a header row before the tables that say:

Clinical characterization was computed using the cohort of [put cohort definition name]  (n= [get cohort count using 'select count_value from heracles_results where analysis_id = 1 and cohort_definition_id = [id]" ])

Make the link on the cohort name open CIRCE to that cohort id

**Comment by anthonysena** [comment]
This is now being displayed based on the exposed cohort.
