### ISSUE TITLE
OHDSI study listing for PENELOPE Observational Evidence section

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Penelope#46]
I added a table, PENELOPE_COHORT_STUDY which provides the listing of all OHDSI studies mapped to the drugs included in the study.  The table fields COHORT_DEFINITION_ID, STUDY_TYPE, STUDY_NAME, STUDY_URL.   I have populated the table with contents for our demo drugs with the protocols available to OHDSI community.

STUDY_TYPE = 1 for Clinical Characterization, 2 for population-level estimation, 3 for patient-level prediction.

The SQL to call the appropriate records is:

--for the clinical characterization section,  @study_type = 1
--for the population-level estimation @study_type = 2
--for patient-level prediction @study_type = 3

SELECT study_name, study_url FROM PENELOPE_COHORT_STUDY WHERE study_type = @study_type AND cohort_definition_id = @cohort_definition_id;

Within each section under Observational Evidence tab, we should have a table display that lists the study name and study URL for any study that meet the criteria. 

If easier for Symposium to include content direct, rather than making it dynamic, that's fine.  All content is in table (only 6 rows).

**Comment by anthonysena** [comment]
This is now part of the Penelope functionality
